app = "ssh-portfolio"
primary_region = "cdg"

[build]

[env]
  SSH_PORT = "2222"

[[services]]
  internal_port = 2222
  protocol = "tcp"
  proxy_proto = false

  [[services.ports]]
    port = 22
    handlers = []

  [[services.tcp_checks]]
    grace_period = "15s"
    interval = "30s"
    timeout = "5s"
